### ISSUE TITLE
Missing content from About Us

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Sabine-Theme-Custom---27-April#13]
The content is missing from about us page
https://6va67losr7xtchu1-63149801689.shopifypreview.com/pages/about-us

![image](https://user-images.githubusercontent.com/97726944/165443384-88f1554a-4fa2-43b0-928e-7bd394794761.png)

**Comment by ui-kuldeep** [comment]
content is not provided.
