### ISSUE TITLE
Images are cropping in collection page

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Sabine-Theme-Custom---27-April#29]
Some images are coming cropped in collection & homepage.

![image](https://user-images.githubusercontent.com/97726944/165465147-a25a2551-b7cd-4a74-8920-01b48c37ab4a.png)

Live

![image](https://user-images.githubusercontent.com/97726944/165465207-3b96fb96-21e2-4fb0-a68b-996a62f6711d.png)

**Comment by ui-kuldeep** [comment]
products have different-different size resolution 
so if i use  css property 'object-fit:cover' then it will be fine but img will be CROPPED otherwise products tiles will not align proper.
