### ISSUE TITLE
Cropped images & less spacing

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Sabine-Theme-Custom---27-April#32]
the images are coming cropped in mobile & also there is less spacing between the products.

![image](https://user-images.githubusercontent.com/97726944/165467859-6957f3d6-9775-4d4a-b209-69fc486b16aa.png)

**Comment by ui-kuldeep** [comment]
products have different-different size resolution 
so if i use  css property 'object-fit:cover' then it will be fine but img will be CROPPED otherwise products tiles will not align proper.
