### ISSUE TITLE
Hamburger menu inside Home Essentials

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Sabine-Theme-Custom---27-April#34]
The hamburger menu is showing Home & decor but the title/name is changed in all the pages. (Home & Living).

![image](https://user-images.githubusercontent.com/97726944/166218523-6d612ce1-0240-45d7-bdcb-ce3b130e2903.png)

![image](https://user-images.githubusercontent.com/97726944/166218559-ff0dbb77-5b7e-4c88-9747-52279214ed77.png)

![image](https://user-images.githubusercontent.com/97726944/166218634-b1e99e4c-d20f-4a79-87e3-20ec282c86fe.png)

**Comment by Gyanendraky** [comment]
It has been updated.
