### ISSUE TITLE
Cropped images 

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Sabine-Theme-Custom---27-April#39]
The collection page & you may also like images are coming cropped in Desktop & iPad.

![image](https://user-images.githubusercontent.com/97726944/166223830-96b0301b-484b-4f67-b1df-f684cbff853f.png)

![image](https://user-images.githubusercontent.com/97726944/166223963-eae7022d-de5b-4db0-8bd9-7b6cdb623fab.png)

**Comment by ui-kuldeep** [comment]
products have different-different size resolution 
so if i use  css property 'object-fit:cover' then it will be fine but img will be CROPPED otherwise products tiles will not align proper.
