### ISSUE TITLE
Spacing in MAC Safari

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Sabine-Theme-Custom---27-April#40]
Space is coming on the left & right side in MAC safari browser.
![image](https://user-images.githubusercontent.com/97726944/166226198-9a038da0-7556-407b-aebf-d1904be5f271.png)

![image](https://user-images.githubusercontent.com/97726944/166226619-76c8d0aa-eb3c-45bb-a9fe-360fc06f3a51.png)

**Comment by ui-kuldeep** [comment]
this is not issue , this is container-width.
